//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTwitter.Resources.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UITextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UITextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("InTwitter.Resources.Localization.UITextResources", typeof(UITextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddNameToBlacklist {
            get {
                return ResourceManager.GetString("AddNameToBlacklist", resourceCulture);
            }
        }
        
        internal static string AddToBlackList {
            get {
                return ResourceManager.GetString("AddToBlackList", resourceCulture);
            }
        }
        
        internal static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        internal static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string CreateYourAccount {
            get {
                return ResourceManager.GetString("CreateYourAccount", resourceCulture);
            }
        }
        
        internal static string DeleteAllBookmarks {
            get {
                return ResourceManager.GetString("DeleteAllBookmarks", resourceCulture);
            }
        }
        
        internal static string DeleteAllBookmarksMessage {
            get {
                return ResourceManager.GetString("DeleteAllBookmarksMessage", resourceCulture);
            }
        }
        
        internal static string DontMatch {
            get {
                return ResourceManager.GetString("DontMatch", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string GetYourAccount {
            get {
                return ResourceManager.GetString("GetYourAccount", resourceCulture);
            }
        }
        
        internal static string GoBackPostMessage {
            get {
                return ResourceManager.GetString("GoBackPostMessage", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string HomeTabTitle {
            get {
                return ResourceManager.GetString("HomeTabTitle", resourceCulture);
            }
        }
        
        internal static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        internal static string LikedPost {
            get {
                return ResourceManager.GetString("LikedPost", resourceCulture);
            }
        }
        
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        internal static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        internal static string MutedProfiles {
            get {
                return ResourceManager.GetString("MutedProfiles", resourceCulture);
            }
        }
        
        internal static string MuteMessage {
            get {
                return ResourceManager.GetString("MuteMessage", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        internal static string NoResultFor {
            get {
                return ResourceManager.GetString("NoResultFor", resourceCulture);
            }
        }
        
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        internal static string NotBlacklistMessage {
            get {
                return ResourceManager.GetString("NotBlacklistMessage", resourceCulture);
            }
        }
        
        internal static string NotBookmarksMessage {
            get {
                return ResourceManager.GetString("NotBookmarksMessage", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string NotMutedListMessage {
            get {
                return ResourceManager.GetString("NotMutedListMessage", resourceCulture);
            }
        }
        
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PleaseConfirmPassword {
            get {
                return ResourceManager.GetString("PleaseConfirmPassword", resourceCulture);
            }
        }
        
        internal static string PleaseTypePassword {
            get {
                return ResourceManager.GetString("PleaseTypePassword", resourceCulture);
            }
        }
        
        internal static string PleaseTypeYourEmail {
            get {
                return ResourceManager.GetString("PleaseTypeYourEmail", resourceCulture);
            }
        }
        
        internal static string PleaseTypeYourName {
            get {
                return ResourceManager.GetString("PleaseTypeYourName", resourceCulture);
            }
        }
        
        internal static string PleaseTypeYourPassword {
            get {
                return ResourceManager.GetString("PleaseTypeYourPassword", resourceCulture);
            }
        }
        
        internal static string PopularThemes {
            get {
                return ResourceManager.GetString("PopularThemes", resourceCulture);
            }
        }
        
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        internal static string ProfileInBlackList {
            get {
                return ResourceManager.GetString("ProfileInBlackList", resourceCulture);
            }
        }
        
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string RemoveFromBlacklist {
            get {
                return ResourceManager.GetString("RemoveFromBlacklist", resourceCulture);
            }
        }
        
        internal static string RemoveFromMuteMessage {
            get {
                return ResourceManager.GetString("RemoveFromMuteMessage", resourceCulture);
            }
        }
        
        internal static string RemoveNameFromBlackList {
            get {
                return ResourceManager.GetString("RemoveNameFromBlackList", resourceCulture);
            }
        }
        
        internal static string SavedPost {
            get {
                return ResourceManager.GetString("SavedPost", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        internal static string StartWriting {
            get {
                return ResourceManager.GetString("StartWriting", resourceCulture);
            }
        }
        
        internal static string SuccessSaveImageMessage {
            get {
                return ResourceManager.GetString("SuccessSaveImageMessage", resourceCulture);
            }
        }
        
        internal static string ThisUserWillNotSeeYourPost {
            get {
                return ResourceManager.GetString("ThisUserWillNotSeeYourPost", resourceCulture);
            }
        }
        
        internal static string UnableSaveImageMessage {
            get {
                return ResourceManager.GetString("UnableSaveImageMessage", resourceCulture);
            }
        }
        
        internal static string UnableShareImageMessage {
            get {
                return ResourceManager.GetString("UnableShareImageMessage", resourceCulture);
            }
        }
        
        internal static string UnableUpdateFeedMessage {
            get {
                return ResourceManager.GetString("UnableUpdateFeedMessage", resourceCulture);
            }
        }
        
        internal static string Unmute {
            get {
                return ResourceManager.GetString("Unmute", resourceCulture);
            }
        }
        
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        internal static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        internal static string WrongName {
            get {
                return ResourceManager.GetString("WrongName", resourceCulture);
            }
        }
        
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        internal static string YouNeedPassword {
            get {
                return ResourceManager.GetString("YouNeedPassword", resourceCulture);
            }
        }
        
        internal static string YouWillSeePostsFeedmessage {
            get {
                return ResourceManager.GetString("YouWillSeePostsFeedmessage", resourceCulture);
            }
        }
        
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
    }
}
